### ISSUE TITLE
svgtoipe ValueError

### ISSUE THREAD

**Issue by ngeri** [otfried/ipe-tools#37]
Hi! Could you help me what could be wrong? Does my svg have some issue in path definition? It seems right with Preview on mac.

Output of the command:
```
Traceback (most recent call last):
  File "svgtoipe.py", line 1042, in <module>
    main()
  File "svgtoipe.py", line 1037, in main
    svg.parse_svg(args.outfile)
  File "svgtoipe.py", line 441, in parse_svg
    self.write_data()
  File "svgtoipe.py", line 458, in write_data
    self.parse_nodes(self.root)
  File "svgtoipe.py", line 470, in parse_nodes
    getattr(self, nodeName)(n)
  File "svgtoipe.py", line 976, in node_path
    parse_path(self.out, d)
  File "svgtoipe.py", line 184, in parse_path
    x1, y1 = pnext(d, 2)
  File "svgtoipe.py", line 156, in pnext
    l.append(float(d.pop(0)))
ValueError: could not convert string to float: L
```

 Here is an example path from the svg file
```
<path d="M101 0a4.68 4.68 0 0 0-1.19.17l-.64.28L100.74 7l-22.89.05C63.55 7.1 47.31 5 35.13 5.33s-27.9 5.14-27.9 5.14l-2.51.69C1.19 12.13 0 29 0 41.75v1.23C0 55.72 1.19 72.6 4.72 73.57l2.51.7S23 79 35.13 79.4s28.42-1.77 42.72-1.74h22.89l-1.59 6.57.64.28a4.27 4.27 0 0 0 1.19.17 2.85 2.85 0 0 0 .49 0h.17l.18-.05.34-.13a2.6 2.6 0 0 0 .88-.6 1.37 1.37 0 0 0 .27-.42l2.23-5.73h20.16c4.39 2.19 8.35 2 13.5 2 24.44 0 34.41-15.88 34.3-36.93v-.43-.43C173.61 20.88 163.64 5 139.2 5c-5.15 0-9.11-.22-13.5 2h-20.16l-2.23-5.74a1.22 1.22 0 0 0-.31-.39 2.6 2.6 0 0 0-.88-.6l-.34-.13h-.35A2.15 2.15 0 0 0 101 0z" fill="#53a1d9"/>
```

**Comment by otfried** [comment]
My guess is that the parser doesn't handle numbers without leading digits (e.g. `-.64.28` for two coordinates).

Can you attach the entire svg file so that I can try to fix it?

**Comment by ngeri** [comment]
Here you go:
```
<?xml version="1.0" encoding="UTF-8"?>
<svg viewBox="0 0 173.5 84.73" xmlns="http://www.w3.org/2000/svg" xmlns:svg="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
	<g>
  	<title>Layer 1</title>
    <path d="M101 0a4.68 4.68 0 0 0-1.19.17l-.64.28L100.74 7l-22.89.05C63.55 7.1 47.31 5 35.13 5.33s-27.9 5.14-27.9 5.14l-2.51.69C1.19 12.13 0 29 0 41.75v1.23C0 55.72 1.19 72.6 4.72 73.57l2.51.7S23 79 35.13 79.4s28.42-1.77 42.72-1.74h22.89l-1.59 6.57.64.28a4.27 4.27 0 0 0 1.19.17 2.85 2.85 0 0 0 .49 0h.17l.18-.05.34-.13a2.6 2.6 0 0 0 .88-.6 1.37 1.37 0 0 0 .27-.42l2.23-5.73h20.16c4.39 2.19 8.35 2 13.5 2 24.44 0 34.41-15.88 34.3-36.93v-.43-.43C173.61 20.88 163.64 5 139.2 5c-5.15 0-9.11-.22-13.5 2h-20.16l-2.23-5.74a1.22 1.22 0 0 0-.31-.39 2.6 2.6 0 0 0-.88-.6l-.34-.13h-.35A2.15 2.15 0 0 0 101 0z" fill="#53a1d9"/>
    <path d="M60 66.33a156.31 156.31 0 0 0-15.65.91c2.92 5.54 9.13 6.34 18.13 6.21A12.6 12.6 0 0 1 60 66.33zM62.41 66.31a12.52 12.52 0 0 0 2.76 7.07c4.91-.14 10.54-.44 16.84-.36 9.11.11 16.42.34 22.29.43-8.54-4.22-24.08-7.06-41.89-7.14z" fill="#fff" opacity="0.52"/>
    <path d="M170.39 61.22l-.93.11c-4 .46-6.91 4.76-7.2 10l-.07 1.31 1-.89a29.49 29.49 0 0 0 6.81-9.68l.38-.85z" id="path3707" fill="#e6bd3c"/>
    <path d="M121.21 71.19h-.06a.5.5 0 0 1 0-1h.06c1.44 0 28.76-.14 42.33-9.78 3-2.12 4.61-7.27 5.16-9.39-3.07 1.25-13.11 5.32-17.24 6.82-4.68 1.71-19.21 5.84-19.36 5.88a.51.51 0 0 1-.62-.35.5.5 0 0 1 .35-.61c.14 0 14.65-4.16 19.29-5.86 4.86-1.77 18-7.12 18.11-7.17a.5.5 0 0 1 .51.08.49.49 0 0 1 .17.48c-.07.33-1.69 8-5.79 10.93-13.82 9.78-41.44 9.97-42.91 9.97z" fill="#2a292a" opacity="0.1"/>
    <path d="M36.05 20.85l-14.26 2.29c-5 .8-9 8.94-9.35 19.23.37 10.28 4.37 18.43 9.35 19.22l14.26 2.29a4.39 4.39 0 0 0 4.4-4.4V25.25a4.39 4.39 0 0 0-4.4-4.4z" fill="#fff" opacity="0.52"/>
    <path d="M115.18 14.57a7.94 7.94 0 0 0-1.61.18L101.85 17C98.6 18.22 96 19.62 96 22.87v39c0 3.25 2.61 4.66 5.86 5.87l11.7 2.26a7.29 7.29 0 0 0 1.61.18c8.33 0 15.07-10.52 15.1-27.79s-6.77-27.8-15.1-27.8z" fill="#fff" opacity="0.52"/>
    <path d="M62.39 18.42c17.82-.08 33.37-2.92 41.91-7.14-5.87.09-13.18.33-22.29.43-6.25.08-11.85-.21-16.73-.36a11.35 11.35 0 0 0-2.89 7.07zM62.63 11.29c-9.11-.15-15.38.63-18.32 6.21 4.89.54 10.16.84 15.64.9a11.73 11.73 0 0 1 2.68-7.11z" fill="#fff" opacity="0.52"/>
    <path d="M170.39 23.69l-.93-.1c-4-.47-6.91-4.77-7.2-10l-.07-1.3 1 .89a29.56 29.56 0 0 1 6.81 9.66l.38.85z" id="path4161" fill="#e6bd3c"/>
    <path d="M169.42 35a.43.43 0 0 1-.19 0c-.13 0-13.25-5.4-18.11-7.17C146.48 26.13 132 22 131.83 22a.5.5 0 1 1 .27-1c.15 0 14.68 4.17 19.36 5.88 4.13 1.51 14.17 5.57 17.24 6.82-.56-2.12-2.18-7.27-5.16-9.39-13.87-9.85-42.11-9.79-42.38-9.78a.5.5 0 0 1 0-1c.3 0 28.84-.07 43 10 4.1 2.91 5.72 10.6 5.79 10.93a.49.49 0 0 1-.17.48.47.47 0 0 1-.36.06z" fill="#2a292a" opacity="0.1"/>
	</g>
</svg>
```

**Comment by otfried** [comment]
Here is a version that works for me.   You'll need Python3 for this one.

[svgtoipe.zip](https://github.com/otfried/ipe-tools/files/3244916/svgtoipe.zip)

**Comment by ngeri** [comment]
Nice! 🤩 It is working for me as well! Thanks
