### ISSUE TITLE
iPython support?

### ISSUE THREAD

**Issue by Langosh6976** [otfried/ipe-tools#6]
Hi,

not sure if it should count as a real issue, more of a wish or just putting this information out for other people. I am using matplotlib version 1.4.2 in Spyder 2.3.5.2, which uses iPython for compiling by default. After noticing that I could directly export my figures directly to my favorite graphical format, I was really thrilled, but I was still getting the following error:

 ```
runfile('/home/michal/.spyder2/temp.py', wdir='/home/michal/.spyder2')
Traceback (most recent call last):

  File "<ipython-input-5-2d271459364a>", line 1, in <module>
    runfile('/home/michal/.spyder2/temp.py', wdir='/home/michal/.spyder2')

  File "/usr/lib/python2.7/dist-packages/spyderlib/widgets/externalshell/sitecustomize.py", line 685, in runfile
    execfile(filename, namespace)

  File "/usr/lib/python2.7/dist-packages/spyderlib/widgets/externalshell/sitecustomize.py", line 78, in execfile
    builtins.execfile(filename, *where)

  File "/home/michal/.spyder2/temp.py", line 14, in <module>
    plt.savefig("my_plot.ipe", format="ipe")

  File "/usr/lib/python2.7/dist-packages/matplotlib/pyplot.py", line 577, in savefig
    res = fig.savefig(*args, **kwargs)

  File "/usr/lib/python2.7/dist-packages/matplotlib/figure.py", line 1470, in savefig
    self.canvas.print_figure(*args, **kwargs)

  File "/usr/lib/python2.7/dist-packages/matplotlib/backend_bases.py", line 2102, in print_figure
    canvas = self._get_output_canvas(format)

  File "/usr/lib/python2.7/dist-packages/matplotlib/backend_bases.py", line 2044, in _get_output_canvas
    '%s.' % (format, ', '.join(formats)))

ValueError: Format "ipe" is not supported.
Supported formats: eps, jpeg, jpg, pdf, pgf, png, ps, raw, rgba, svg, svgz, tif, tiff.
```
Which I figured was just the backend not loading. After I have put the backend into every possible place, a colleague (who was failing to reproduce my problem, since he was just using python in console) noticed that I was using iPython for compiling. After switching to Python, the problem was gone.

**Comment by otfried** [comment]
Are you starting iPython from the command line?  Try giving the option: 
```
-dmodule://backend_ipe
```
when you start iPython.

Or install the Ipe backend properly into your system.  backend_ipe.py should go where the other backends are (/usr/lib/python2.7/dist-packages/matplotlib/backends judging from the output above).  You will need to register the backend by adding a line in **file_type** in backend_bases.py, and make a function 

```
    def print_pgf(self, *args, **kwargs):
        from backends.backend_ipe import FigureCanvasIpe  # lazy import
        ipe = self.switch_backends(FigureCanvasIpe)
        return ipe.print_ipe(*args, **kwargs)
```

**Comment by Langosh6976** [comment]
When I start the iPython from the commandline, without any options, working at home directory
 ```
In [2]: import matplotlib

In [3]: matplotlib.use('module://backend_ipe')

In [4]: import matplotlib.pyplot as plt

In [5]: plt.figure()
Out[5]: <matplotlib.figure.Figure at 0x7f881c9db050>

In [6]: plt.savefig("my_plot.ipe", format="ipe")
 ```
Correctly produces the *ipe* file. When I do the same inside of Spyder iPython console, I receive the same error as mentioned above. In the Python console, this is not the case.
Regarding proper installation of the backend, I have copied it into the /backends/, however the is no method **print_eps** in my **backend_bases.py** (attached as .txt). The print functions are called differently, I however lack the expertise to implement it properly.

[backend_bases.txt](https://github.com/otfried/ipe-tools/files/45599/backend_bases.txt)

**Comment by otfried** [comment]
If you edit `backend_bases.py` and insert ipe in the two tables `_default_filetypes` and `_default_backends` as follows, it should work (I cannot try it because I have a completely different version of matplotlib - which version are you using?):

```
_default_filetypes = {
    'ipe' : 'Ipe figure',
    'ps': 'Postscript',
    'eps': 'Encapsulated Postscript',
    'pdf': 'Portable Document Format',
    'pgf': 'PGF code for LaTeX',
    'png': 'Portable Network Graphics',
    'raw': 'Raw RGBA bitmap',
    'rgba': 'Raw RGBA bitmap',
    'svg': 'Scalable Vector Graphics',
    'svgz': 'Scalable Vector Graphics'
}


_default_backends = {
    'ipe' : 'matplotlib.backends.backend_ipe',
    'ps': 'matplotlib.backends.backend_ps',
    'eps': 'matplotlib.backends.backend_ps',
    'pdf': 'matplotlib.backends.backend_pdf',
    'pgf': 'matplotlib.backends.backend_pgf',
    'png': 'matplotlib.backends.backend_agg',
    'raw': 'matplotlib.backends.backend_agg',
    'rgba': 'matplotlib.backends.backend_agg',
    'svg': 'matplotlib.backends.backend_svg',
    'svgz': 'matplotlib.backends.backend_svg',
}
```

**Comment by Langosh6976** [comment]
I am using matplotlib 1.4.2. I have tried the edit as you suggested, but sadly with the same result.
I have tried to delete the backend from home directory and again try to run it from terminal:
```
michal@michal-ESPRIMO-P920:~$ ipython
Python 2.7.10 (default, Oct 14 2015, 16:09:02) 
Type "copyright", "credits" or "license" for more information.

IPython 2.3.0 -- An enhanced Interactive Python.
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.

In [1]: import matplotlib

In [2]: matplotlib.use('module://backend_ipe')

In [3]: import matplotlib.pyplot as plt
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-3-eff513f636fd> in <module>()
----> 1 import matplotlib.pyplot as plt

/usr/lib/python2.7/dist-packages/matplotlib/pyplot.py in <module>()
    107 
    108 from matplotlib.backends import pylab_setup
--> 109 _backend_mod, new_figure_manager, draw_if_interactive, _show = pylab_setup()
    110 
    111 

/usr/lib/python2.7/dist-packages/matplotlib/backends/__init__.pyc in pylab_setup()
     30     # imports. 0 means only perform absolute imports.
     31     backend_mod = __import__(backend_name,
---> 32                              globals(),locals(),[backend_name],0)
     33 
     34     # Things we pull in from all backends

ImportError: No module named backend_ipe
```
Even though the backend_ipe.py is sitting happily in `/usr/lib/python2.7/dist-packages/matplotlib/backends`.

**Comment by otfried** [comment]
Once you registered the backend_ipe as I described (by modifying backend_bases), you need to **remove** the line `matplotlib.use('module://backend_ipe')` from your code.

**Comment by otfried** [comment]
Matplotlib should load the backend automatically based on the `format="ipe"` in your save command.

**Comment by Langosh6976** [comment]
Right, sorry, could've thought of that. After doing that:
```
michal@michal-ESPRIMO-P920:~$ ipython
Python 2.7.10 (default, Oct 14 2015, 16:09:02) 
Type "copyright", "credits" or "license" for more information.

IPython 2.3.0 -- An enhanced Interactive Python.
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.

In [1]: import matplotlib

In [2]: import matplotlib.pyplot as plt

In [3]: plt.figure()
Out[3]: <matplotlib.figure.Figure at 0x7fc53225f450>

In [4]: plt.savefig('test.ipe', format='ipe')
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-4-a181debedf92> in <module>()
----> 1 plt.savefig('test.ipe', format='ipe')

/usr/lib/python2.7/dist-packages/matplotlib/pyplot.pyc in savefig(*args, **kwargs)
    575 def savefig(*args, **kwargs):
    576     fig = gcf()
--> 577     res = fig.savefig(*args, **kwargs)
    578     draw()   # need this if 'transparent=True' to reset colors
    579     return res

/usr/lib/python2.7/dist-packages/matplotlib/figure.pyc in savefig(self, *args, **kwargs)
   1468             self.set_frameon(frameon)
   1469 
-> 1470         self.canvas.print_figure(*args, **kwargs)
   1471 
   1472         if frameon:

/usr/lib/python2.7/dist-packages/matplotlib/backend_bases.py in print_figure(self, filename, dpi, facecolor, edgecolor, orientation, format, **kwargs)
   2102 
   2103         # get canvas object and print method for format
-> 2104         canvas = self._get_output_canvas(format)
   2105         print_method = getattr(canvas, 'print_%s' % format)
   2106 

/usr/lib/python2.7/dist-packages/matplotlib/backend_bases.py in _get_output_canvas(self, format)
   2036 
   2037         # check if there is a default canvas for the requested format
-> 2038         canvas_class = get_registered_canvas_class(format)
   2039         if canvas_class:
   2040             return self.switch_backends(canvas_class)

/usr/lib/python2.7/dist-packages/matplotlib/backend_bases.py in get_registered_canvas_class(format)
    129     backend_class = _default_backends[format]
    130     if cbook.is_string_like(backend_class):
--> 131         backend_class = import_module(backend_class).FigureCanvas
    132         _default_backends[format] = backend_class
    133     return backend_class

AttributeError: 'module' object has no attribute 'FigureCanvas'
```

**Comment by otfried** [comment]
Can you try again (by downloading a new copy of backend_ipe.py) ?

**Comment by Langosh6976** [comment]
Works as a charm, thanks a lot!
